name: Rust

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install dependency
      run: cargo install cargo-llvm-cov
    - name: check versions
      run: |
        rustup --version
        cargo --version
        cargo llvm-cov --version
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests and collect coverage data
      run: cargo llvm-cov --no-report --workspace

    - name: Generate HTML coverage report
      run: cargo llvm-cov --html --output-dir ./target/coverage

    - name: Generate LCOV and check coverage thresholds
      run: |
        cargo llvm-cov \
          --lcov --output-path ./lcov.info \
          --fail-under-lines 33 \
          --fail-under-functions 33
